#!/usr/bin/expect -f
#
# Expect script for starting the server and running an autoplay session.

# Start server with autoplay, wait until it's done.
set server_pid [spawn node launcher-autoplay.js]
set server_id $spawn_id
set timeout 600
expect {
    timeout { puts "\nERROR: Server is not finishing!"; exit 1 }

    "lgc100> game over.\r"
}

# Stop server.
exec kill $server_pid
close -i $server_id
wait -i $server_id

puts "\nThe server ran successfully."

exit 0
